version: '3.8'

services:
  dashboard:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    command: streamlit run dashboard_coinbase.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    depends_on:
      bitcoin-stream:
        condition: service_healthy
      coinbase-stream:
        condition: service_healthy

  bitcoin-stream:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_KEY}
    command: python stream_bitcoin.py
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'python stream_bitcoin.py' || exit 1"]
      interval: 30s

  coinbase-stream:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    command: python stream_bitcoin_coinbase.py
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'python stream_bitcoin_coinbase.py' || exit 1"]
      interval: 30s